menu:
    Blog: /
    Archives: /archives
    rss: /atom.xml
    linkedin: https://www.linkedin.com/in/chenxiliuk
    Github: https://github.com/moremeds

favicon: /satellite.ico
logo: /logo.ico

# comment
disqus: chenxili
duoshuo:

ga: UA-71835528-1